# Generated by Django 4.2.4 on 2025-07-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approved',
        ),
    ]
